// Code generated by pegomock. DO NOT EDIT.
// Source: view_interface.go

package view

import (
	pegomock "github.com/petergtz/pegomock"
	"reflect"
	"time"
)

type MockvalidatorInterface struct {
	fail func(message string, callerSkip ...int)
}

func NewMockvalidatorInterface(options ...pegomock.Option) *MockvalidatorInterface {
	mock := &MockvalidatorInterface{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockvalidatorInterface) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockvalidatorInterface) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockvalidatorInterface) validateLetterColoring(l *LettersToColor) error {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockvalidatorInterface().")
	}
	params := []pegomock.Param{l}
	result := pegomock.GetGenericMockFrom(mock).Invoke("validateLetterColoring", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockvalidatorInterface) VerifyWasCalledOnce() *VerifierMockvalidatorInterface {
	return &VerifierMockvalidatorInterface{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockvalidatorInterface) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockvalidatorInterface {
	return &VerifierMockvalidatorInterface{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockvalidatorInterface) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockvalidatorInterface {
	return &VerifierMockvalidatorInterface{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockvalidatorInterface) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockvalidatorInterface {
	return &VerifierMockvalidatorInterface{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockvalidatorInterface struct {
	mock                   *MockvalidatorInterface
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockvalidatorInterface) validateLetterColoring(l *LettersToColor) *MockvalidatorInterface_validateLetterColoring_OngoingVerification {
	params := []pegomock.Param{l}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "validateLetterColoring", params, verifier.timeout)
	return &MockvalidatorInterface_validateLetterColoring_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockvalidatorInterface_validateLetterColoring_OngoingVerification struct {
	mock              *MockvalidatorInterface
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockvalidatorInterface_validateLetterColoring_OngoingVerification) GetCapturedArguments() *LettersToColor {
	l := c.GetAllCapturedArguments()
	return l[len(l)-1]
}

func (c *MockvalidatorInterface_validateLetterColoring_OngoingVerification) GetAllCapturedArguments() (_param0 []*LettersToColor) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]*LettersToColor, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(*LettersToColor)
		}
	}
	return
}
